[package]
name = "seeded_rand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

sha1 = "0.10"
rand = "0.8"
rand_chacha = "0.3"
lazy_static = "1.4"
twox-hash = "1.6"